package br.org.sae.service;

public enum RespostaMatricula {
	
	MATRICULA_SUCESSO,
	MATRICULA_INVALIDA,
	MATRICULA_INVALIDA_VAGAS_INDISPONIVEIS,
	MATRICULA_INVALIDA_NAO_PRESTOU_VESTIBULINHO,
	MATRICULA_INVALIDA_MATRICULA_JA_EXISTENTE,
	MATRICULA_INVALIDA_JA_MATRICULADO_NO_MESMO_PERIODO,
	REMATRICULA_SUCESSO,
	REMATRICULA_INVALIDA,
	CANCELAMENTO_SUCESSO,
	TRANCAMENTO_SUCESSO,
	REMANEJAMENTO_INVALIDO_VAGAS_INDISPONIVEIS,
	REMANEJAMENTO_SUCESSO,
	TRANSFERENCIA_SUCESSO,
	DESISTENCIA_SUCESSO,
	ERRO_DESCONHECIDO

}
