package br.org.sae.service;

public enum RespostaMatricula {
	
	MATRICULA_SUCESSO,
	MATRICULA_INVALIDA,
	REMATRICULA_SUCESSO,
	REMATRICULA_INVALIDA,
	CANCELAMENTO_SUCESSO,
	TRANCAMENTO_SUCESSO,
	REMANEJAMENTO_SUCESSO,
	TRANSFERENCIA_SUCESSO,
	DESISTENCIA_SUCESSO,
	ERRO_DESCONHECIDO

}
