package br.org.sae.importador;

public interface ImportadorConstants {
	
	int CANDIDATO_NOME = 7;
	int CANDIDATO_RG_NUMERO = 8;
	int CANDIDATO_RG_ORGAO_EXPED = 9;
	int CANDIDATO_SEXO = 10;
	int CANDIDATO_DT_NASCIMENTO = 11;
	int CANDIDATO_ESTADO_CIVIL = 12;
	int CANDIDATO_AFRODESCENDENTE = 23;
	int CANDIDATO_ESCOLARIDADE = 24;
	int CANDIDATO_EMAIL = 26;
	int CANDIDATO_NECESSIDADE = 27;
	int CANDIDATO_NECESSIDADE_TIPO = 28;
	int CANDIDATO_CPF = 66;
	
	int VESTIBULINHO_TIPO_PROVA = 29;
	int VESTIBULINHO_NOTA = 42;
	
	int CURSO1_NOME = 2;
	int CURSO1_PERIODO = 25;
	int CURSO1_CLASSIFICACAO = 43;

	int CURSO2_NOME = 62;
	int CURSO2_PERIODO = 63;
	int CURSO2_CLASSIFICACAO = 64;

	int TELEFONE_P_DDD = 17;
	int TELEFONE_P_NUMERO = 18;
	int TELEFONE_P_RAMAL = 19;

	int TELEFONE_S_DDD = 30;
	int TELEFONE_S_NUMERO = 31;
	int TELEFONE_S_RAMAL = 32;
	
	int ENDERECO_LOGRADOURO = 13;
	int ENDERECO_NUMERO = 14;
	int ENDERECO_COMPLEMENTO = 15;
	int ENDERECO_BAIRRO = 16;
	int ENDERECO_CIDADE = 20;
	int ENDERECO_UF = 21;
	int ENDERECO_CEP = 22;

}
